{
 "title": "wet-lab-system-health",
 "tags": [
  "wetlab",
  "system",
  "openshift"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Wet1 CPU Temp",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by(instance) (node_hwmon_temp_celsius{chip=\"platform_coretemp_0\", instance=\"c0-47-0e-20-70-42\"})",
     "legendFormat": "CPU Temp"
    }
   ]
  },
  {
   "title": "Wet2 CPU Temp",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by(instance) (node_hwmon_temp_celsius{chip=\"platform_coretemp_0\", instance=\"c0-47-0e-20-70-5c\"})",
     "legendFormat": "CPU Temp"
    }
   ]
  },
  {
   "title": "Wet3 CPU Temp",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by(instance) (node_hwmon_temp_celsius{chip=\"platform_coretemp_0\", instance=\"server4.selab.mad.redhat.com\"})",
     "legendFormat": "CPU Temp"
    }
   ]
  },
  {
   "title": "Wet1 RAM Usage",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{instance=\"c0-47-0e-20-70-42\"} / node_memory_MemTotal_bytes{instance=\"c0-47-0e-20-70-42\"})) * 100",
     "legendFormat": "RAM Usage"
    }
   ]
  },
  {
   "title": "Wet2 RAM Usage",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{instance=\"c0-47-0e-20-70-5c\"} / node_memory_MemTotal_bytes{instance=\"c0-47-0e-20-70-5c\"})) * 100",
     "legendFormat": "RAM Usage"
    }
   ]
  },
  {
   "title": "Wet3 RAM Usage",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{instance=\"server4.selab.mad.redhat.com\"} / node_memory_MemTotal_bytes{instance=\"server4.selab.mad.redhat.com\"})) * 100",
     "legendFormat": "RAM Usage"
    }
   ]
  },
  {
   "title": "Wet1 System Load",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_load1{instance=\"c0-47-0e-20-70-42\"}",
     "legendFormat": "System Load"
    }
   ]
  },
  {
   "title": "Wet2 System Load",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_load1{instance=\"c0-47-0e-20-70-5c\"}",
     "legendFormat": "System Load"
    }
   ]
  },
  {
   "title": "Wet3 System Load",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_load1{instance=\"server4.selab.mad.redhat.com\"}",
     "legendFormat": "System Load"
    }
   ]
  }
 ]
}